import { primaryWhite, primaryBlack, strawBerry } from '@/constants/style-variable';

export const CodeTheme: { [key: string]: React.CSSProperties } = {
  'code[class*="language-"]': {
    color: primaryWhite,
    background: 'none',
    textShadow: '0 1px rgba(0, 0, 0, 0.3)',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: primaryWhite,
    background: primaryBlack,
    textShadow: '0 1px rgba(0, 0, 0, 0.3)',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '0.675rem',
    overflow: 'auto',
    borderRadius: '0.375em',
  },
  ':not(pre) > code[class*="language-"]': {
    background: primaryBlack,
    padding: '0.675rem',
    borderRadius: '.375em',
    whiteSpace: 'normal',
  },
  comment: { color: '#7a7e85' },
  prolog: { color: '#7a7e85' },
  doctype: { color: '#7a7e85' },
  cdata: { color: '#7a7e85' },
  punctuation: { color: '#f8f8f2' },
  '.namespace': { opacity: '.7' },
  property: { color: '#f4728a' },
  tag: { color: strawBerry },
  constant: { color: '#f4728a' },
  symbol: { color: '#f4728a' },
  deleted: { color: '#ff6b6b' },
  boolean: { color: '#d4a5ff' },
  number: { color: '#d4a5ff' },
  selector: { color: strawBerry },
  'attr-name': { color: '#ffb3c0' },
  string: { color: '#ffd9a0' },
  char: { color: '#ffd9a0' },
  builtin: { color: strawBerry },
  inserted: { color: '#a8e6cf' },
  operator: { color: '#f8f8f2' },
  entity: { color: '#f8f8f2', cursor: 'help' },
  url: { color: '#ffb3c0' },
  '.language-css .token.string': { color: '#ffd9a0' },
  '.style .token.string': { color: '#ffd9a0' },
  variable: { color: '#f8f8f2' },
  atrule: { color: '#ffd9a0' },
  'attr-value': { color: '#ffd9a0' },
  function: { color: strawBerry },
  'class-name': { color: '#ffb3c0' },
  keyword: { color: '#f4728a' },
  regex: { color: '#ffb3c0' },
  important: { color: strawBerry, fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
